
[package]
name = "lyte-fuzz"
version = "0.0.0"
authors = ["Taylor Holliday"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lyte = { path = "../" }

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"
test = false
doc = false
