use crate::*;
use std::collections::HashSet;

/// Type checking errors generated by
/// both the type checker and constraint
/// solver.
#[derive(Clone, Debug)]
pub struct TypeError {
    pub location: Loc,
    pub message: String,
}

/// Local variable declaration.
#[derive(Copy, Clone, Debug)]
struct Var {
    name: Name,
    ty: TypeID,
    mutable: bool,
}

/// Type-checks ASTs.
pub struct Checker {
    /// Overloads for arithmetic with built-in types.
    arith_overloads: Vec<TypeID>,

    /// Overloads for casting.
    cast_overloads: Vec<TypeID>,

    /// Constraints on types.
    constraints: Vec<Constraint>,

    /// Current type variable instance.
    inst: Instance,

    /// Is an expression assignable?
    lvalue: Vec<bool>,

    /// Overloads for negation of built-in types.
    neg_overloads: Vec<TypeID>,

    /// Next anonymous type variable index.
    next_anon: usize,

    /// Overloads for relational operations with built-in types.
    rel_overloads: Vec<TypeID>,

    /// Expression types.
    pub types: Vec<TypeID>,

    /// Currently declared vars, as we're checking.
    vars: Vec<Var>,

    /// Accumulated type errors while checking.
    pub errors: Vec<TypeError>,
}

/// Returns true if the type is or contains a slice (unsized array `[T]`).
///
/// Slices are only allowed as function parameters, not in struct fields or return types.
/// For function types, only the return type is checked (slice parameters are fine).
fn type_contains_bad_slice(ty: TypeID) -> bool {
    match &*ty {
        Type::Slice(_) => true,
        Type::Array(elem, _) => type_contains_bad_slice(*elem),
        Type::Tuple(types) => types.iter().any(|t| type_contains_bad_slice(*t)),
        Type::Func(_, ret) => type_contains_bad_slice(*ret),
        _ => false,
    }
}

/// Returns true if `ty` would be infinite in size due to a recursive struct definition.
///
/// `visiting` is the set of struct names currently on the DFS stack. Seed it with the
/// name of the struct being checked so that any path back to it is detected as a cycle.
fn type_is_recursive(ty: TypeID, decls: &DeclTable, visiting: &mut HashSet<Name>) -> bool {
    match &*ty {
        Type::Name(name, type_args) => {
            if visiting.contains(name) {
                return true;
            }
            // Only structs can contribute to infinite size; enums etc. are skipped.
            let struct_info: Option<(Vec<Name>, Vec<Field>)> =
                decls.find(*name).iter().find_map(|d| {
                    if let Decl::Struct(s) = d {
                        Some((s.typevars.clone(), s.fields.clone()))
                    } else {
                        None
                    }
                });
            if let Some((typevars, fields)) = struct_info {
                // Substitute generic parameters so we follow the concrete field types.
                let inst: Instance = typevars
                    .iter()
                    .zip(type_args.iter())
                    .map(|(tv, t)| (mk_type(Type::Var(*tv)), *t))
                    .collect();
                visiting.insert(*name);
                let recursive = fields
                    .iter()
                    .any(|f| type_is_recursive(f.ty.subst(&inst), decls, visiting));
                visiting.remove(name);
                recursive
            } else {
                false
            }
        }
        Type::Array(elem, _) => type_is_recursive(*elem, decls, visiting),
        Type::Tuple(types) => types.iter().any(|t| type_is_recursive(*t, decls, visiting)),
        _ => false,
    }
}

impl Default for Checker {
    fn default() -> Self {
        Self::new()
    }
}

impl Checker {
    pub fn new() -> Self {
        let int8 = mk_type(Type::Int8);
        let int32: TypeID = mk_type(Type::Int32);
        let uint32: TypeID = mk_type(Type::UInt32);
        let types = [Type::Int32, Type::UInt32, Type::Float32];
        let mut arith_overloads = vec![];
        let mut rel_overloads = vec![];
        let mut neg_overloads = vec![];
        let b = mk_type(Type::Bool);

        for ty in types {
            let t = mk_type(ty);
            let tt = tuple(vec![t, t]);
            arith_overloads.push(func(tt, t));
            rel_overloads.push(func(tt, b));
            neg_overloads.push(func(t, t));
        }

        let cast_overloads = vec![
            func(int8, int32),
            func(int32, int8),
            func(int32, uint32),
            func(uint32, int32),
        ];

        Self {
            types: vec![],
            lvalue: vec![],
            inst: Instance::new(),
            next_anon: 0,
            vars: vec![],
            arith_overloads,
            rel_overloads,
            neg_overloads,
            cast_overloads,
            constraints: vec![],
            errors: vec![],
        }
    }

    fn eq(&mut self, lhs: TypeID, rhs: TypeID, loc: Loc, _error_message: &str) {
        self.add_constraint(Constraint::Equal(lhs, rhs, loc));
    }

    fn fresh(&mut self) -> TypeID {
        let t = mk_type(Type::Anon(self.next_anon));
        self.next_anon += 1;
        t
    }

    fn add_constraint(&mut self, c: Constraint) {
        // println!("adding constraint {:?}", &c);
        self.constraints.push(c);
    }

    fn check_unop(
        &mut self,
        id: ExprID,
        op: Unop,
        arg: ExprID,
        arena: &ExprArena,
        decls: &DeclTable,
    ) -> TypeID {
        let argt = self.check_expr(arg, arena, decls);

        match op {
            Unop::Neg => {
                let ft = self.fresh();
                let types = vec![mk_type(Type::Int32), mk_type(Type::Float32)];
                let alts: Vec<_> = types
                    .iter()
                    .map(|t| Alt {
                        ty: func(*t, *t),
                        interfaces: vec![],
                    })
                    .collect();

                self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

                let r = self.fresh();

                self.eq(
                    func(argt, r),
                    ft,
                    arena.locs[id],
                    &format!("no match for unary negation on {}", argt),
                );

                r
            }
            Unop::Not => {
                self.eq(
                    argt,
                    mk_type(Type::Bool),
                    arena.locs[id],
                    &"logical negation requires a boolean",
                );

                mk_type(Type::Bool)
            }
        }
    }

    fn check_binop(
        &mut self,
        id: ExprID,
        op: Binop,
        lhs: ExprID,
        rhs: ExprID,
        arena: &ExprArena,
        decls: &DeclTable,
    ) -> TypeID {
        let at = self.check_expr(lhs, arena, decls);
        let bt = self.check_expr(rhs, arena, decls);

        if op.equality() {
            self.eq(
                at,
                bt,
                arena.locs[id],
                &format!(
                    "equality operator requres equal types, got {} and {}",
                    at, bt
                ),
            );

            mk_type(Type::Bool)
        } else if let Binop::Assign = op {
            if !self.lvalue[lhs] {
                self.errors.push(TypeError {
                    location: arena.locs[id],
                    message: "left-hand side of assignment isn't assignable".to_string(),
                });
            }

            self.eq(
                at,
                bt,
                arena.locs[id],
                &format!(
                    "assignment operator requres equal types, got {} and {}",
                    at, bt
                ),
            );

            at
        } else if op.arithmetic() {
            let ft = self.fresh();

            let mut alts = vec![];

            for ty in &self.arith_overloads {
                alts.push(Alt {
                    ty: *ty,
                    interfaces: vec![],
                });
            }

            let overload_name = Name::new(op.overload_name().into());
            for d in decls.find(overload_name) {
                if let Decl::Func(_) = d {
                    let dt = d.ty().fresh(&mut self.next_anon);
                    alts.push(Alt {
                        ty: dt,
                        interfaces: vec![],
                    });
                }
            }

            self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

            let r = self.fresh();

            self.eq(
                func(tuple(vec![at, bt]), r),
                ft,
                arena.locs[id],
                &format!("no match for arithemtic between {} and {}", at, bt),
            );

            r
        } else if op.relational() {
            let ft = self.fresh();

            let mut alts = vec![];

            for ty in &self.rel_overloads {
                alts.push(Alt {
                    ty: *ty,
                    interfaces: vec![],
                });
            }

            self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

            let b = mk_type(Type::Bool);

            self.eq(
                func(tuple(vec![at, bt]), b),
                ft,
                arena.locs[id],
                &format!("no match for relational between {} and {}", at, bt),
            );

            b
        } else {
            self.fresh()
        }
    }

    fn check_expr(&mut self, id: ExprID, arena: &ExprArena, decls: &DeclTable) -> TypeID {
        let ty = match &arena[id] {
            Expr::True | Expr::False => mk_type(Type::Bool),
            Expr::Int(_) => {
                let ty = self.fresh();
                let alts = vec![
                    Alt {
                        ty: mk_type(Type::Int32),
                        interfaces: vec![],
                    },
                    // Alt {ty: mk_type(Type::UInt32), interfaces: vec![]},
                ];
                self.add_constraint(Constraint::Or(ty, alts, arena.locs[id]));
                ty
            }
            Expr::UInt(_) => mk_type(Type::UInt32),
            Expr::Real(_) => mk_type(Type::Float32),
            Expr::Char(_) => mk_type(Type::Int8),
            Expr::String(s) => {
                let int8 = mk_type(Type::Int8);
                mk_type(Type::Array(int8, ArraySize::Known(s.bytes().len() as i32 + 1)))
            }
            Expr::Id(name) => {
                // Local variables will override all declarations.
                // Is this what we want?
                if let Some(v) = self.find(*name) {
                    self.lvalue[id] = v.mutable;
                    v.ty
                } else if let Some(Decl::Global { ty, .. }) = decls.find(*name).first() {
                    self.lvalue[id] = true;
                    *ty
                } else {
                    let t = self.fresh();
                    let alts: Vec<Alt> = decls
                        .alts(*name)
                        .iter()
                        .map(|alt| alt.fresh(&mut self.next_anon))
                        .collect();

                    if alts.is_empty() {
                        self.errors.push(TypeError {
                            location: arena.locs[id],
                            message: format!("undeclared identifier: {}", *name),
                        });
                    }

                    self.add_constraint(Constraint::Or(t, alts, arena.locs[id]));
                    t
                }
            }
            Expr::Unop(op, a) => self.check_unop(id, *op, *a, arena, decls),
            Expr::Binop(op, a, b) => self.check_binop(id, *op, *a, *b, arena, decls),
            Expr::AsTy(e, ty) => {
                let et = self.check_expr(*e, arena, decls);

                let ft = self.fresh();

                let mut alts = vec![];
                for ty in &self.cast_overloads {
                    alts.push(Alt {
                        ty: *ty,
                        interfaces: vec![],
                    });
                }

                self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

                self.eq(
                    func(et, *ty),
                    ft,
                    arena.locs[id],
                    &format!("no match for cast between {} and {}", et, ty),
                );

                *ty
            }
            Expr::Call(f, args) => {
                let lhs = self.check_expr(*f, arena, decls);

                let ret = self.fresh();
                let v1 = self.fresh();
                self.eq(
                    self.types[*f],
                    func(v1, ret),
                    arena.locs[id],
                    "attempt to call a non-function",
                );

                let mut arg_types = vec![];
                for e in args {
                    self.check_expr(*e, arena, decls);
                    arg_types.push(self.types[*e]);
                }

                let ft = func(tuple(arg_types), ret);

                self.eq(
                    lhs,
                    ft,
                    arena.locs[id],
                    &format!(
                        "arguments ({:?}) don't match function ({:?})",
                        find(lhs, &self.inst),
                        find(ft, &self.inst)
                    ),
                );

                ret
            }
            Expr::Macro(name, args) => {
                let mut found = false;
                let mut macro_type = mk_type(Type::Void);

                // XXX: overloaded macros?
                for d in decls.find(*name) {
                    if let Decl::Macro(_) = d {
                        // Found our macro.
                        found = true;
                        macro_type = d.ty().fresh(&mut self.next_anon);
                    }
                }

                if !found {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: format!("unknown macro: {}", *name),
                    });
                }

                let mut arg_types = vec![];
                for e in args {
                    self.check_expr(*e, arena, decls);
                    arg_types.push(self.types[*e]);
                }

                let ret = self.fresh();
                let ft = func(tuple(arg_types), ret);

                self.eq(
                    macro_type,
                    ft,
                    arena.locs[id],
                    "arguments don't match macro definition",
                );

                ret
            }
            Expr::Field(lhs, name) => {
                let lhs_t = self.check_expr(*lhs, arena, decls);

                self.lvalue[id] = self.lvalue[*lhs];

                let t = self.fresh();

                self.constraints
                    .push(Constraint::Field(lhs_t, *name, t, arena.locs[id]));

                t
            }
            Expr::Enum(name) => {
                let t = self.fresh();
                let mut alts = vec![];

                // Find all the enum declarations with that name.
                decls.find_enum(*name, &mut |enum_name| {
                    let enum_ty = mk_type(Type::Name(enum_name, vec![]));
                    alts.push(Alt {
                        ty: enum_ty,
                        interfaces: vec![],
                    });
                });

                self.constraints
                    .push(Constraint::Or(t, alts, arena.locs[id]));

                t
            }
            Expr::Block(exprs) => {
                let n = self.vars.len();
                let mut t = mk_type(Type::Void);
                for e in exprs {
                    t = self.check_expr(*e, arena, decls);
                }
                while self.vars.len() > n {
                    self.vars.pop();
                }
                t
            }
            Expr::Var(name, init, ty) => {
                let ty = if let Some(ty) = ty { *ty } else { self.fresh() };

                if let Some(e) = init {
                    let init_ty = self.check_expr(*e, arena, decls);

                    self.eq(
                        ty,
                        init_ty,
                        arena.locs[id],
                        "variable initializer type must match",
                    );
                }

                self.vars.push(Var {
                    name: *name,
                    ty,
                    mutable: true,
                });

                ty
            }
            Expr::Let(name, init, ty) => {
                let ty = if let Some(ty) = ty { *ty } else { self.fresh() };

                let init_ty = self.check_expr(*init, arena, decls);

                self.eq(
                    ty,
                    init_ty,
                    arena.locs[id],
                    "variable initializer type must match",
                );

                self.vars.push(Var {
                    name: *name,
                    ty,
                    mutable: true,
                });

                ty
            }
            Expr::Arena(block) => self.check_expr(*block, arena, decls),
            Expr::Return(expr) => self.check_expr(*expr, arena, decls),
            Expr::ArrayLiteral(exprs) => {
                if exprs.is_empty() {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: "empty array literals are not allowed".to_string(),
                    });
                }
                let t = self.fresh();
                for e in exprs {
                    let elem_t = self.check_expr(*e, arena, decls);
                    self.constraints
                        .push(Constraint::Equal(t, elem_t, arena.locs[*e]));
                }
                mk_type(Type::Array(t, ArraySize::Known(exprs.len() as i32)))
            }
            Expr::ArrayIndex(array_expr, index_expr) => {
                let t = self.fresh();
                let array_t = self.check_expr(*array_expr, arena, decls);
                let idx_t = self.check_expr(*index_expr, arena, decls);

                // Arrays always mutable?
                self.lvalue[id] = true;

                // Probably should allow both signed and unsigned indexing?
                // self.eq(
                //     idx_t,
                //     mk_type(Type::Int32),
                //     arena.locs[*index_expr],
                //     "array index must be an i32",
                // );

                let alts: Vec<Alt> = vec![
                    Alt {
                        ty: mk_type(Type::Int32),
                        interfaces: vec![],
                    },
                    Alt {
                        ty: mk_type(Type::UInt32),
                        interfaces: vec![],
                    },
                ];

                self.add_constraint(Constraint::Or(idx_t, alts, arena.locs[*index_expr]));

                self.add_constraint(Constraint::ArrayOf(
                    array_t,
                    t,
                    arena.locs[*array_expr],
                ));
                t
            }
            Expr::Array(value, size) => {
                let value_t = self.check_expr(*value, arena, decls);
                let size_t = self.check_expr(*size, arena, decls);

                self.eq(
                    size_t,
                    mk_type(Type::Int32),
                    arena.locs[*size],
                    "array size must be an i32",
                );

                mk_type(Type::Array(value_t, ArraySize::Known(0)))
            }
            Expr::While(cond, body) => {
                let cond_t = self.check_expr(*cond, arena, decls);
                self.eq(
                    cond_t,
                    mk_type(Type::Bool),
                    arena.locs[*cond],
                    "while loop control must be a bool",
                );
                self.check_expr(*body, arena, decls);
                mk_type(Type::Void)
            }
            Expr::If(cond, then_expr, else_expr) => {
                let t = self.fresh();
                let cond_t = self.check_expr(*cond, arena, decls);
                self.eq(
                    cond_t,
                    mk_type(Type::Bool),
                    arena.locs[*cond],
                    "if expression conditional must be a bool",
                );
                self.check_expr(*then_expr, arena, decls);
                if let Some(else_expr) = else_expr {
                    self.check_expr(*else_expr, arena, decls);
                }
                t
            }
            Expr::For {
                var,
                start,
                end,
                body,
            } => {
                let ty = mk_type(Type::Int32);
                let start_t = self.check_expr(*start, arena, decls);
                let end_t = self.check_expr(*end, arena, decls);
                self.eq(
                    start_t,
                    ty,
                    arena.locs[*start],
                    "start of for loop must be an integer",
                );
                self.eq(
                    end_t,
                    ty,
                    arena.locs[*start],
                    "end of for loop must be an integer",
                );

                self.vars.push(Var {
                    name: *var,
                    ty,
                    mutable: false,
                });

                self.check_expr(*body, arena, decls);

                self.vars.pop();

                mk_type(Type::Void)
            }
            Expr::Tuple(exprs) => {
                let mut types = vec![];
                for e in exprs {
                    types.push(self.check_expr(*e, arena, decls));
                }
                mk_type(Type::Tuple(types))
            }
            Expr::Lambda { params, body } => {
                let n = self.vars.len();
                let mut param_types = vec![];
                for param in params {
                    let ty = param.ty.unwrap_or_else(|| self.fresh());
                    self.vars.push(Var {
                        name: param.name,
                        mutable: false,
                        ty,
                    });
                    param_types.push(ty);
                }

                let rt = self.check_expr(*body, arena, decls);

                while self.vars.len() > n {
                    self.vars.pop();
                }

                func(tuple(param_types), rt)
            }
            _ => {
                println!("haven't yet implemented {:?}", &arena[id]);
                panic!();
            }
        };
        self.types[id] = ty;
        ty
    }

    fn find(&self, name: Name) -> Option<Var> {
        for v in &self.vars {
            if v.name == name {
                return Some(*v);
            }
        }
        None
    }

    fn check_fn_decl(&mut self, func_decl: &FuncDecl, decls: &DeclTable) {
        // Disallow slice types in return position.
        if type_contains_bad_slice(func_decl.ret) {
            self.errors.push(TypeError {
                location: func_decl.loc,
                message: format!(
                    "slice type {} is not allowed as a return type",
                    func_decl.ret.pretty_print()
                ),
            });
        }

        let n = func_decl.arena.exprs.len();
        self.types.resize(n, mk_type(Type::Void));
        self.lvalue.resize(n, false);

        if let Some(body) = func_decl.body {
            // println!("🟧 checking function {:?} 🟧", *func_decl.name);

            self.inst.clear();
            self.constraints.clear();

            for param in &func_decl.params {
                self.vars.push(Var {
                    name: param.name,
                    ty: param.ty.unwrap(),
                    mutable: false,
                });
            }

            // Size variables are available as i32 values in the body.
            for &sv in &func_decl.size_vars {
                self.vars.push(Var {
                    name: sv,
                    ty: mk_type(Type::Int32),
                    mutable: false,
                });
            }

            // Add interface functions to available functions.
            for constraint in &func_decl.constraints {
                if let Some(Decl::Interface(interface)) =
                    decls.find(constraint.interface_name).first()
                {
                    let mut inst = Instance::new();

                    interface
                        .typevars
                        .iter()
                        .zip(&constraint.typevars)
                        .for_each(|pair| {
                            let t0 = mk_type(Type::Var(*pair.0));
                            let t1 = mk_type(Type::Var(*pair.1));
                            inst.insert(t0, t1);
                        });

                    for func in &interface.funcs {
                        self.vars.push(Var {
                            name: func.name,
                            ty: func.ty().subst(&inst),
                            mutable: false,
                        });
                    }
                } else {
                    self.errors.push(TypeError {
                        location: func_decl.loc,
                        message: format!("unknown interface: {}", constraint.interface_name),
                    })
                }
            }

            // Check the body of the function.
            let ty = self.check_expr(body, &func_decl.arena, decls);

            if func_decl.ret != mk_type(Type::Void) {
                self.eq(
                    ty,
                    func_decl.ret,
                    func_decl.arena.locs[body],
                    "return type must match function return type",
                );
            }

            self.vars.clear();

            if self.errors.is_empty() {
                solve_constraints(
                    &mut self.constraints,
                    &mut self.inst,
                    decls,
                    &mut self.errors,
                );
            }

            //println!("instance:");
            //print_instance(&self.inst);
        }
    }

    fn check_struct_decl(&mut self, st: &StructDecl, decls: &DeclTable) {
        let mut names = HashSet::new();

        for field in &st.fields {
            if names.contains(&field.name) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!("repeated field: {}", &field.name),
                })
            } else {
                names.insert(field.name);
            }

            field.ty.typevars(&mut |name| {
                if !st.typevars.iter().any(|n| *n == name) {
                    self.errors.push(TypeError {
                        location: field.loc,
                        message: format!("unknown type variable: {}", name),
                    })
                }
            })
        }

        // Disallow slice types in struct fields.
        for field in &st.fields {
            if type_contains_bad_slice(field.ty) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!(
                        "slice type {} is not allowed in struct fields (use a sized array instead)",
                        field.ty.pretty_print()
                    ),
                })
            }
        }

        // Disallow recursive struct definitions (they would be unbounded in size).
        let mut visiting = HashSet::new();
        visiting.insert(st.name);
        for field in &st.fields {
            if type_is_recursive(field.ty, decls, &mut visiting) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!("struct '{}' is recursive", st.name),
                });
                break;
            }
        }
    }

    fn check_interface(&mut self, _name: Name, funcs: &[FuncDecl]) {
        for func in funcs {
            if func.body.is_some() {
                self.errors.push(TypeError {
                    location: func.loc,
                    message: format!("interface function can't have body: {}", func.name),
                })
            }
        }
    }

    fn _check_decl(&mut self, decl: &Decl, decls: &DeclTable) {
        match decl {
            Decl::Func(func_decl) => self.check_fn_decl(func_decl, decls),
            Decl::Macro(func_decl) => self.check_fn_decl(func_decl, decls),
            Decl::Interface(Interface { name, funcs, .. }) => self.check_interface(*name, funcs),
            Decl::Struct(struct_decl) => self.check_struct_decl(struct_decl, decls),
            _ => (),
        }
    }

    pub fn check(&mut self, decls: &DeclTable) {
        for decl in &decls.decls {
            self._check_decl(decl, decls);
            // After type-checking each function, verify closures don't escape.
            if let Decl::Func(fd) | Decl::Macro(fd) = decl {
                check_escape_in_func(fd, &mut self.errors);
            }
        }
    }

    pub fn check_decl(&mut self, decl: &Decl, decls: &DeclTable) {
        self._check_decl(decl, decls);
        if let Decl::Func(fd) | Decl::Macro(fd) = decl {
            check_escape_in_func(fd, &mut self.errors);
        }
    }

    /// Returns types we've solved for.
    pub fn solved_types(&self) -> Vec<TypeID> {
        self.types.iter().map(|t| t.subst(&self.inst)).collect()
    }

    pub fn print_errors(&self) {
        for err in &self.errors {
            print_error_with_context(err.location, &err.message);
        }
    }
}

/// Verify that no capturing lambda (one with free variables from the enclosing
/// function) escapes the function, either directly returned or via a variable.
/// Such a closure would capture stack addresses that dangle after the frame exits.
fn check_escape_in_func(func_decl: &FuncDecl, errors: &mut Vec<TypeError>) {
    let Some(body) = func_decl.body else { return; };
    let mut scope: HashSet<String> = func_decl.params.iter()
        .map(|p| p.name.to_string())
        .collect();
    let mut tainted: HashSet<String> = HashSet::new();
    escape_walk(body, &func_decl.arena, &mut scope, &mut tainted, errors);
}

/// Walk `expr` tracking:
/// - `scope`: all names declared in the enclosing function (used by lambda capture detection)
/// - `tainted`: names that are bound to a capturing lambda and must not be returned
fn escape_walk(
    expr: ExprID,
    arena: &ExprArena,
    scope: &mut HashSet<String>,
    tainted: &mut HashSet<String>,
    errors: &mut Vec<TypeError>,
) {
    match &arena[expr] {
        Expr::Return(e) => {
            // Walk first so any declarations inside `e` update `tainted`.
            escape_walk(*e, arena, scope, tainted, errors);
            if expr_is_tainted(*e, arena, scope, tainted) {
                errors.push(TypeError {
                    location: arena.locs[*e],
                    message: "closure with captured variables cannot be returned \
                              (captured addresses would dangle after the frame exits)"
                        .to_string(),
                });
            }
        }
        Expr::Lambda { .. } => {
            // Do not recurse into the lambda body — it is a separate scope.
        }
        Expr::Block(exprs) => {
            let saved = scope.clone();
            for e in exprs {
                escape_walk(*e, arena, scope, tainted, errors);
            }
            *scope = saved;
        }
        Expr::Let(name, init, _) => {
            escape_walk(*init, arena, scope, tainted, errors);
            if expr_is_tainted(*init, arena, scope, tainted) {
                tainted.insert(name.to_string());
            }
            scope.insert(name.to_string());
        }
        Expr::Var(name, init, _) => {
            if let Some(init_id) = init {
                escape_walk(*init_id, arena, scope, tainted, errors);
                if expr_is_tainted(*init_id, arena, scope, tainted) {
                    tainted.insert(name.to_string());
                }
            }
            scope.insert(name.to_string());
        }
        Expr::Assign(lhs, rhs) => {
            escape_walk(*rhs, arena, scope, tainted, errors);
            if expr_is_tainted(*rhs, arena, scope, tainted) {
                tainted.insert(lhs.to_string());
            } else {
                tainted.remove(&lhs.to_string());
            }
        }
        Expr::If(cond, then, else_) => {
            escape_walk(*cond, arena, scope, tainted, errors);
            escape_walk(*then, arena, scope, tainted, errors);
            if let Some(e) = else_ {
                escape_walk(*e, arena, scope, tainted, errors);
            }
        }
        Expr::While(cond, body) => {
            escape_walk(*cond, arena, scope, tainted, errors);
            escape_walk(*body, arena, scope, tainted, errors);
        }
        Expr::For { start, end, body, .. } => {
            escape_walk(*start, arena, scope, tainted, errors);
            escape_walk(*end, arena, scope, tainted, errors);
            escape_walk(*body, arena, scope, tainted, errors);
        }
        Expr::Call(f, args) => {
            escape_walk(*f, arena, scope, tainted, errors);
            for a in args {
                escape_walk(*a, arena, scope, tainted, errors);
            }
        }
        Expr::Binop(_, lhs, rhs) => {
            escape_walk(*lhs, arena, scope, tainted, errors);
            escape_walk(*rhs, arena, scope, tainted, errors);
        }
        Expr::Unop(_, arg) => escape_walk(*arg, arena, scope, tainted, errors),
        Expr::Field(e, _) | Expr::AsTy(e, _) | Expr::Arena(e) => {
            escape_walk(*e, arena, scope, tainted, errors);
        }
        Expr::ArrayIndex(arr, idx) | Expr::Array(arr, idx) => {
            escape_walk(*arr, arena, scope, tainted, errors);
            escape_walk(*idx, arena, scope, tainted, errors);
        }
        Expr::ArrayLiteral(elems) | Expr::Tuple(elems) => {
            for e in elems {
                escape_walk(*e, arena, scope, tainted, errors);
            }
        }
        Expr::Macro(_, args) => {
            for a in args {
                escape_walk(*a, arena, scope, tainted, errors);
            }
        }
        _ => {}
    }
}

/// Returns true if `expr` might produce a capturing lambda value:
/// - a lambda literal whose body references names from `scope` beyond its own params
/// - an identifier in `tainted` (bound to a capturing lambda earlier)
/// - a block or if/else whose value branch is tainted
fn expr_is_tainted(
    expr: ExprID,
    arena: &ExprArena,
    scope: &HashSet<String>,
    tainted: &HashSet<String>,
) -> bool {
    match &arena[expr] {
        Expr::Lambda { params, body } => {
            let lambda_params: HashSet<String> = params.iter()
                .map(|p| p.name.to_string())
                .collect();
            lambda_has_captures(*body, arena, &lambda_params, scope)
        }
        Expr::Id(name) => tainted.contains(&name.to_string()),
        Expr::Block(exprs) => exprs.last()
            .map_or(false, |e| expr_is_tainted(*e, arena, scope, tainted)),
        Expr::If(_, then, else_) => {
            expr_is_tainted(*then, arena, scope, tainted)
                || else_.map_or(false, |e| expr_is_tainted(e, arena, scope, tainted))
        }
        // Conservatively: if a tainted value flows into a call (as the function
        // expression or as any argument), the result is also considered tainted.
        // This catches laundering patterns like `return launder(f)` where `f` is
        // a capturing lambda.
        Expr::Call(fn_expr, args) => {
            expr_is_tainted(*fn_expr, arena, scope, tainted)
                || args.iter().any(|a| expr_is_tainted(*a, arena, scope, tainted))
        }
        _ => false,
    }
}

/// Returns true if `body` (the lambda body) references any name that is in
/// `outer_scope` but not in `lambda_params`.
fn lambda_has_captures(
    body: ExprID,
    arena: &ExprArena,
    lambda_params: &HashSet<String>,
    outer_scope: &HashSet<String>,
) -> bool {
    match &arena[body] {
        Expr::Id(name) => {
            let s = name.to_string();
            outer_scope.contains(&s) && !lambda_params.contains(&s)
        }
        Expr::Assign(name, rhs) => {
            let s = name.to_string();
            (outer_scope.contains(&s) && !lambda_params.contains(&s))
                || lambda_has_captures(*rhs, arena, lambda_params, outer_scope)
        }
        Expr::Binop(_, lhs, rhs) => {
            lambda_has_captures(*lhs, arena, lambda_params, outer_scope)
                || lambda_has_captures(*rhs, arena, lambda_params, outer_scope)
        }
        Expr::Unop(_, arg) => lambda_has_captures(*arg, arena, lambda_params, outer_scope),
        Expr::Call(f, args) => {
            lambda_has_captures(*f, arena, lambda_params, outer_scope)
                || args.iter().any(|a| lambda_has_captures(*a, arena, lambda_params, outer_scope))
        }
        Expr::Block(exprs) => {
            exprs.iter().any(|e| lambda_has_captures(*e, arena, lambda_params, outer_scope))
        }
        Expr::If(cond, then, else_) => {
            lambda_has_captures(*cond, arena, lambda_params, outer_scope)
                || lambda_has_captures(*then, arena, lambda_params, outer_scope)
                || else_.map(|e| lambda_has_captures(e, arena, lambda_params, outer_scope))
                       .unwrap_or(false)
        }
        Expr::Return(e) | Expr::Field(e, _) | Expr::AsTy(e, _) | Expr::Arena(e) => {
            lambda_has_captures(*e, arena, lambda_params, outer_scope)
        }
        Expr::While(cond, body) | Expr::ArrayIndex(cond, body) | Expr::Array(cond, body) => {
            lambda_has_captures(*cond, arena, lambda_params, outer_scope)
                || lambda_has_captures(*body, arena, lambda_params, outer_scope)
        }
        Expr::For { start, end, body, .. } => {
            lambda_has_captures(*start, arena, lambda_params, outer_scope)
                || lambda_has_captures(*end, arena, lambda_params, outer_scope)
                || lambda_has_captures(*body, arena, lambda_params, outer_scope)
        }
        Expr::Let(_, init, _) => lambda_has_captures(*init, arena, lambda_params, outer_scope),
        Expr::Var(_, init, _) => init
            .map(|e| lambda_has_captures(e, arena, lambda_params, outer_scope))
            .unwrap_or(false),
        Expr::ArrayLiteral(elems) | Expr::Tuple(elems) => elems
            .iter()
            .any(|e| lambda_has_captures(*e, arena, lambda_params, outer_scope)),
        Expr::Macro(_, args) => args
            .iter()
            .any(|a| lambda_has_captures(*a, arena, lambda_params, outer_scope)),
        Expr::Lambda { params, body } => {
            // Nested lambda: extend lambda_params with nested params.
            let mut inner_params = lambda_params.clone();
            for p in params {
                inner_params.insert(p.name.to_string());
            }
            lambda_has_captures(*body, arena, &inner_params, outer_scope)
        }
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub fn check(s: &str) -> Vec<TypeError> {
        let mut errors = vec![];
        let decls = parse_program_str(&s, &mut errors);
        assert!(errors.is_empty());

        let mut result = vec![];

        let table = DeclTable::new(decls);
        for decl in &table.decls {
            let mut type_checker = Checker::new();
            type_checker.check_decl(decl, &table);
            type_checker.print_errors();
            result.append(&mut type_checker.errors);
        }

        result
    }

    #[test]
    pub fn test_recursive_struct_direct() {
        // struct A { x: A } — direct self-reference
        let s = "struct A { x: A }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for recursive struct");
        assert!(errors[0].message.contains("recursive"));
    }

    #[test]
    pub fn test_recursive_struct_indirect() {
        // struct A { b: B }  struct B { a: A } — mutual recursion
        let s = "struct A { b: B }\nstruct B { a: A }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for mutually recursive structs");
    }

    #[test]
    pub fn test_recursive_struct_array() {
        // struct A { x: [A; 5] } — self-reference inside a fixed-size array
        let s = "struct A { x: [A; 5] }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for recursive struct via array");
        assert!(errors[0].message.contains("recursive"));
    }

    #[test]
    pub fn test_non_recursive_struct() {
        // struct Point { x: i32, y: i32 } — not recursive
        let s = "struct Point { x: i32, y: i32 }";
        let errors = check(s);
        assert!(errors.is_empty(), "expected no errors for non-recursive struct");
    }

    #[test]
    pub fn test_non_recursive_struct_field() {
        // struct A { b: B }  struct B { x: i32 } — not recursive
        let s = "struct A { b: B }\nstruct B { x: i32 }";
        let errors = check(s);
        assert!(errors.is_empty(), "expected no errors for non-recursive struct chain");
    }

    #[test]
    pub fn test_array_if() {
        let s = "
        f(i: i32) {
            var a: [i32; 100]
            if i >= 0 && i < 100 {
                a[i]
            }
        }
        ";

        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_inc_i32() {
        let s = "
        f {
            var i: i32
            i = i + 1
        }
        ";

        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_slice_in_struct_field() {
        let s = "struct Bad { x: [i32] }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for slice in struct field");
        assert!(errors[0].message.contains("slice type"));
    }

    #[test]
    pub fn test_slice_return_type() {
        let s = "f(a: [i32]) -> [i32] { a }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for slice return type");
        assert!(errors[0].message.contains("slice type"));
    }

    #[test]
    pub fn test_slice_param_allowed() {
        let s = "f(a: [i32]) -> i32 { a[0] }";
        let errors = check(s);
        assert!(errors.is_empty(), "slice parameters should be allowed");
    }

    #[test]
    pub fn test_nested_slice_in_struct() {
        let s = "struct Bad { x: [[i32]; 5] }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for nested slice in struct field");
        assert!(errors[0].message.contains("slice type"));
    }
}
