use crate::*;
use std::collections::HashSet;

/// Type checking errors generated by
/// both the type checker and constraint
/// solver.
#[derive(Clone, Debug)]
pub struct TypeError {
    pub location: Loc,
    pub message: String,
}

/// Local variable declaration.
#[derive(Copy, Clone, Debug)]
struct Var {
    name: Name,
    ty: TypeID,
    mutable: bool,
}

/// Type-checks ASTs.
pub struct Checker {
    /// Overloads for arithmetic with built-in types.
    arith_overloads: Vec<TypeID>,

    /// Overloads for casting.
    cast_overloads: Vec<TypeID>,

    /// Constraints on types.
    constraints: Vec<Constraint>,

    /// Current type variable instance.
    inst: Instance,

    /// Is an expression assignable?
    lvalue: Vec<bool>,

    /// Overloads for negation of built-in types.
    neg_overloads: Vec<TypeID>,

    /// Next anonymous type variable index.
    next_anon: usize,

    /// Overloads for relational operations with built-in types.
    rel_overloads: Vec<TypeID>,

    /// Expression types.
    pub types: Vec<TypeID>,

    /// Currently declared vars, as we're checking.
    vars: Vec<Var>,

    /// Accumulated type errors while checking.
    pub errors: Vec<TypeError>,

    /// Nesting depth of loops (>0 means we're inside a loop).
    loop_depth: usize,
}

/// Returns true if the type is or contains a slice (unsized array `[T]`).
///
/// Slices are only allowed as function parameters, not in struct fields or return types.
/// For function types, only the return type is checked (slice parameters are fine).
fn type_contains_bad_slice(ty: TypeID) -> bool {
    match &*ty {
        Type::Slice(_) => true,
        Type::Array(elem, _) => type_contains_bad_slice(*elem),
        Type::Tuple(types) => types.iter().any(|t| type_contains_bad_slice(*t)),
        Type::Func(_, ret) => type_contains_bad_slice(*ret),
        _ => false,
    }
}

/// Returns true if `ty` would be infinite in size due to a recursive struct definition.
///
/// `visiting` is the set of struct names currently on the DFS stack. Seed it with the
/// name of the struct being checked so that any path back to it is detected as a cycle.
fn type_is_recursive(ty: TypeID, decls: &DeclTable, visiting: &mut HashSet<Name>) -> bool {
    match &*ty {
        Type::Name(name, type_args) => {
            if visiting.contains(name) {
                return true;
            }
            // Only structs can contribute to infinite size; enums etc. are skipped.
            let struct_info: Option<(Vec<Name>, Vec<Field>)> =
                decls.find(*name).iter().find_map(|d| {
                    if let Decl::Struct(s) = d {
                        Some((s.typevars.clone(), s.fields.clone()))
                    } else {
                        None
                    }
                });
            if let Some((typevars, fields)) = struct_info {
                // Substitute generic parameters so we follow the concrete field types.
                let inst: Instance = typevars
                    .iter()
                    .zip(type_args.iter())
                    .map(|(tv, t)| (mk_type(Type::Var(*tv)), *t))
                    .collect();
                visiting.insert(*name);
                let recursive = fields
                    .iter()
                    .any(|f| type_is_recursive(f.ty.subst(&inst), decls, visiting));
                visiting.remove(name);
                recursive
            } else {
                false
            }
        }
        Type::Array(elem, _) => type_is_recursive(*elem, decls, visiting),
        Type::Tuple(types) => types.iter().any(|t| type_is_recursive(*t, decls, visiting)),
        _ => false,
    }
}

impl Default for Checker {
    fn default() -> Self {
        Self::new()
    }
}

impl Checker {
    pub fn new() -> Self {
        let int8 = mk_type(Type::Int8);
        let int32: TypeID = mk_type(Type::Int32);
        let uint32: TypeID = mk_type(Type::UInt32);
        let types = [Type::Int32, Type::UInt32, Type::Float32, Type::Float64];
        let mut arith_overloads = vec![];
        let mut rel_overloads = vec![];
        let mut neg_overloads = vec![];
        let b = mk_type(Type::Bool);

        for ty in types {
            let t = mk_type(ty);
            let tt = tuple(vec![t, t]);
            arith_overloads.push(func(tt, t));
            rel_overloads.push(func(tt, b));
            neg_overloads.push(func(t, t));
        }

        let float32 = mk_type(Type::Float32);
        let float64 = mk_type(Type::Float64);
        let cast_overloads = vec![
            func(int8, int32),
            func(int32, int8),
            func(int32, uint32),
            func(uint32, int32),
            func(int32, float32),
            func(float32, int32),
            func(int32, float64),
            func(float64, int32),
            func(float32, float64),
            func(float64, float32),
        ];

        Self {
            types: vec![],
            lvalue: vec![],
            inst: Instance::new(),
            next_anon: 0,
            vars: vec![],
            arith_overloads,
            rel_overloads,
            neg_overloads,
            cast_overloads,
            constraints: vec![],
            errors: vec![],
            loop_depth: 0,
        }
    }

    fn eq(&mut self, lhs: TypeID, rhs: TypeID, loc: Loc, _error_message: &str) {
        self.add_constraint(Constraint::Equal(lhs, rhs, loc));
    }

    fn fresh(&mut self) -> TypeID {
        let t = mk_type(Type::Anon(self.next_anon));
        self.next_anon += 1;
        t
    }

    fn add_constraint(&mut self, c: Constraint) {
        // println!("adding constraint {:?}", &c);
        self.constraints.push(c);
    }

    fn check_unop(
        &mut self,
        id: ExprID,
        op: Unop,
        arg: ExprID,
        arena: &ExprArena,
        decls: &DeclTable,
    ) -> TypeID {
        let argt = self.check_expr(arg, arena, decls);

        match op {
            Unop::Neg => {
                let ft = self.fresh();
                let types = vec![mk_type(Type::Int32), mk_type(Type::Float32)];
                let alts: Vec<_> = types
                    .iter()
                    .map(|t| Alt {
                        ty: func(*t, *t),
                        interfaces: vec![],
                    })
                    .collect();

                self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

                let r = self.fresh();

                self.eq(
                    func(argt, r),
                    ft,
                    arena.locs[id],
                    &format!("no match for unary negation on {}", argt),
                );

                r
            }
            Unop::Not => {
                self.eq(
                    argt,
                    mk_type(Type::Bool),
                    arena.locs[id],
                    &"logical negation requires a boolean",
                );

                mk_type(Type::Bool)
            }
        }
    }

    fn check_binop(
        &mut self,
        id: ExprID,
        op: Binop,
        lhs: ExprID,
        rhs: ExprID,
        arena: &ExprArena,
        decls: &DeclTable,
    ) -> TypeID {
        let at = self.check_expr(lhs, arena, decls);
        let bt = self.check_expr(rhs, arena, decls);

        if op.equality() {
            self.eq(
                at,
                bt,
                arena.locs[id],
                &format!(
                    "equality operator requres equal types, got {} and {}",
                    at, bt
                ),
            );

            mk_type(Type::Bool)
        } else if let Binop::Assign = op {
            // Lvalue check is deferred to check_lvalues() after type solving,
            // so that slice types are fully resolved.

            self.eq(
                at,
                bt,
                arena.locs[id],
                &format!(
                    "assignment operator requres equal types, got {} and {}",
                    at, bt
                ),
            );

            at
        } else if op.arithmetic() {
            let ft = self.fresh();

            let mut alts = vec![];

            for ty in &self.arith_overloads {
                alts.push(Alt {
                    ty: *ty,
                    interfaces: vec![],
                });
            }

            let overload_name = Name::new(op.overload_name().into());
            for d in decls.find(overload_name) {
                if let Decl::Func(_) = d {
                    let dt = d.ty().fresh(&mut self.next_anon);
                    alts.push(Alt {
                        ty: dt,
                        interfaces: vec![],
                    });
                }
            }

            self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

            let r = self.fresh();

            self.eq(
                func(tuple(vec![at, bt]), r),
                ft,
                arena.locs[id],
                &format!("no match for arithemtic between {} and {}", at, bt),
            );

            r
        } else if op.relational() {
            let ft = self.fresh();

            let mut alts = vec![];

            for ty in &self.rel_overloads {
                alts.push(Alt {
                    ty: *ty,
                    interfaces: vec![],
                });
            }

            self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

            let b = mk_type(Type::Bool);

            self.eq(
                func(tuple(vec![at, bt]), b),
                ft,
                arena.locs[id],
                &format!("no match for relational between {} and {}", at, bt),
            );

            b
        } else {
            self.fresh()
        }
    }

    fn check_expr(&mut self, id: ExprID, arena: &ExprArena, decls: &DeclTable) -> TypeID {
        let ty = match &arena[id] {
            Expr::True | Expr::False => mk_type(Type::Bool),
            Expr::Int(_) => {
                let ty = self.fresh();
                let alts = vec![
                    Alt {
                        ty: mk_type(Type::Int32),
                        interfaces: vec![],
                    },
                    // Alt {ty: mk_type(Type::UInt32), interfaces: vec![]},
                ];
                self.add_constraint(Constraint::Or(ty, alts, arena.locs[id]));
                ty
            }
            Expr::UInt(_) => mk_type(Type::UInt32),
            Expr::Real(_) => mk_type(Type::Float32),
            Expr::Char(_) => mk_type(Type::Int8),
            Expr::String(s) => {
                let int8 = mk_type(Type::Int8);
                mk_type(Type::Array(
                    int8,
                    ArraySize::Known(s.bytes().len() as i32 + 1),
                ))
            }
            Expr::Id(name) => {
                // Local variables will override all declarations.
                // Is this what we want?
                if let Some(v) = self.find(*name) {
                    self.lvalue[id] = v.mutable;
                    v.ty
                } else if let Some(Decl::Global { ty, .. }) = decls.find(*name).first() {
                    self.lvalue[id] = true;
                    *ty
                } else {
                    let t = self.fresh();
                    let alts: Vec<Alt> = decls
                        .alts(*name)
                        .iter()
                        .map(|alt| alt.fresh(&mut self.next_anon))
                        .collect();

                    if alts.is_empty() {
                        self.errors.push(TypeError {
                            location: arena.locs[id],
                            message: format!("undeclared identifier: {}", *name),
                        });
                    }

                    self.add_constraint(Constraint::Or(t, alts, arena.locs[id]));
                    t
                }
            }
            Expr::Unop(op, a) => self.check_unop(id, *op, *a, arena, decls),
            Expr::Binop(op, a, b) => self.check_binop(id, *op, *a, *b, arena, decls),
            Expr::AsTy(e, ty) => {
                let et = self.check_expr(*e, arena, decls);

                let ft = self.fresh();

                let mut alts = vec![];
                for ty in &self.cast_overloads {
                    alts.push(Alt {
                        ty: *ty,
                        interfaces: vec![],
                    });
                }

                self.add_constraint(Constraint::Or(ft, alts, arena.locs[id]));

                self.eq(
                    func(et, *ty),
                    ft,
                    arena.locs[id],
                    &format!("no match for cast between {} and {}", et, ty),
                );

                *ty
            }
            Expr::Call(f, args) => {
                let lhs = self.check_expr(*f, arena, decls);

                let ret = self.fresh();
                let v1 = self.fresh();
                self.eq(
                    self.types[*f],
                    func(v1, ret),
                    arena.locs[id],
                    "attempt to call a non-function",
                );

                let mut arg_types = vec![];
                for e in args {
                    self.check_expr(*e, arena, decls);
                    arg_types.push(self.types[*e]);
                }

                let ft = func(tuple(arg_types), ret);

                self.eq(
                    lhs,
                    ft,
                    arena.locs[id],
                    &format!(
                        "arguments ({:?}) don't match function ({:?})",
                        find(lhs, &self.inst),
                        find(ft, &self.inst)
                    ),
                );

                ret
            }
            Expr::Macro(name, args) => {
                let mut found = false;
                let mut macro_type = mk_type(Type::Void);

                // XXX: overloaded macros?
                for d in decls.find(*name) {
                    if let Decl::Macro(_) = d {
                        // Found our macro.
                        found = true;
                        macro_type = d.ty().fresh(&mut self.next_anon);
                    }
                }

                if !found {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: format!("unknown macro: {}", *name),
                    });
                }

                let mut arg_types = vec![];
                for e in args {
                    self.check_expr(*e, arena, decls);
                    arg_types.push(self.types[*e]);
                }

                let ret = self.fresh();
                let ft = func(tuple(arg_types), ret);

                self.eq(
                    macro_type,
                    ft,
                    arena.locs[id],
                    "arguments don't match macro definition",
                );

                ret
            }
            Expr::Field(lhs, name) => {
                let lhs_t = self.check_expr(*lhs, arena, decls);

                self.lvalue[id] = self.lvalue[*lhs];

                let t = self.fresh();

                self.constraints
                    .push(Constraint::Field(lhs_t, *name, t, arena.locs[id]));

                t
            }
            Expr::Enum(name) => {
                let t = self.fresh();
                let mut alts = vec![];

                // Find all the enum declarations with that name.
                decls.find_enum(*name, &mut |enum_name| {
                    let enum_ty = mk_type(Type::Name(enum_name, vec![]));
                    alts.push(Alt {
                        ty: enum_ty,
                        interfaces: vec![],
                    });
                });

                self.constraints
                    .push(Constraint::Or(t, alts, arena.locs[id]));

                t
            }
            Expr::Block(exprs) => {
                let n = self.vars.len();
                let mut t = mk_type(Type::Void);
                for e in exprs {
                    t = self.check_expr(*e, arena, decls);
                }
                while self.vars.len() > n {
                    self.vars.pop();
                }
                t
            }
            Expr::Var(name, init, ty) => {
                let ty = if let Some(ty) = ty { *ty } else { self.fresh() };

                if let Some(e) = init {
                    let init_ty = self.check_expr(*e, arena, decls);

                    self.eq(
                        ty,
                        init_ty,
                        arena.locs[id],
                        "variable initializer type must match",
                    );
                }

                self.vars.push(Var {
                    name: *name,
                    ty,
                    mutable: true,
                });

                ty
            }
            Expr::Let(name, init, ty) => {
                let ty = if let Some(ty) = ty { *ty } else { self.fresh() };

                let init_ty = self.check_expr(*init, arena, decls);

                self.eq(
                    ty,
                    init_ty,
                    arena.locs[id],
                    "variable initializer type must match",
                );

                self.vars.push(Var {
                    name: *name,
                    ty,
                    mutable: false,
                });

                ty
            }
            Expr::Arena(block) => self.check_expr(*block, arena, decls),
            Expr::Return(expr) => self.check_expr(*expr, arena, decls),
            Expr::Break => {
                if self.loop_depth == 0 {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: "break outside of loop".to_string(),
                    });
                }
                mk_type(Type::Void)
            }
            Expr::Continue => {
                if self.loop_depth == 0 {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: "continue outside of loop".to_string(),
                    });
                }
                mk_type(Type::Void)
            }
            Expr::StructLit(struct_name, fields) => {
                // Look up the struct declaration.
                let d = decls.find(*struct_name);
                if let Some(Decl::Struct(st)) = d.first() {
                    // Create fresh type variables for generics.
                    let type_args: Vec<TypeID> =
                        st.typevars.iter().map(|_| self.fresh()).collect();
                    let inst: crate::Instance = st
                        .typevars
                        .iter()
                        .map(|tv| mk_type(Type::Var(*tv)))
                        .zip(type_args.iter().copied())
                        .collect();

                    // Check each field.
                    for (fname, fval) in fields {
                        let val_ty = self.check_expr(*fval, arena, decls);
                        if let Some(field) = st.find_field(fname) {
                            let field_ty = field.ty.subst(&inst);
                            self.eq(
                                val_ty,
                                field_ty,
                                arena.locs[*fval],
                                &format!("struct field '{}' type mismatch", fname),
                            );
                        } else {
                            self.errors.push(TypeError {
                                location: arena.locs[*fval],
                                message: format!(
                                    "struct '{}' has no field '{}'",
                                    struct_name, fname
                                ),
                            });
                        }
                    }

                    // Check all fields are provided.
                    for field in &st.fields {
                        if !fields.iter().any(|(fname, _)| *fname == field.name) {
                            self.errors.push(TypeError {
                                location: arena.locs[id],
                                message: format!(
                                    "missing field '{}' in struct literal '{}'",
                                    field.name, struct_name
                                ),
                            });
                        }
                    }

                    mk_type(Type::Name(*struct_name, type_args))
                } else {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: format!("'{}' is not a struct", struct_name),
                    });
                    self.fresh()
                }
            }
            Expr::ArrayLiteral(exprs) => {
                if exprs.is_empty() {
                    self.errors.push(TypeError {
                        location: arena.locs[id],
                        message: "empty array literals are not allowed".to_string(),
                    });
                }
                let t = self.fresh();
                for e in exprs {
                    let elem_t = self.check_expr(*e, arena, decls);
                    self.constraints
                        .push(Constraint::Equal(t, elem_t, arena.locs[*e]));
                }
                mk_type(Type::Array(t, ArraySize::Known(exprs.len() as i32)))
            }
            Expr::ArrayIndex(array_expr, index_expr) => {
                let t = self.fresh();
                let array_t = self.check_expr(*array_expr, arena, decls);
                let idx_t = self.check_expr(*index_expr, arena, decls);

                // Preliminary lvalue: propagate from array expression.
                // The final check (including slice mutability) is done in
                // check_lvalues() after type solving.
                self.lvalue[id] = self.lvalue[*array_expr];

                // Probably should allow both signed and unsigned indexing?
                // self.eq(
                //     idx_t,
                //     mk_type(Type::Int32),
                //     arena.locs[*index_expr],
                //     "array index must be an i32",
                // );

                let alts: Vec<Alt> = vec![
                    Alt {
                        ty: mk_type(Type::Int32),
                        interfaces: vec![],
                    },
                    Alt {
                        ty: mk_type(Type::UInt32),
                        interfaces: vec![],
                    },
                ];

                self.add_constraint(Constraint::Or(idx_t, alts, arena.locs[*index_expr]));

                self.add_constraint(Constraint::ArrayOf(array_t, t, arena.locs[*array_expr]));
                t
            }
            Expr::Array(value, size) => {
                let value_t = self.check_expr(*value, arena, decls);
                let size_t = self.check_expr(*size, arena, decls);

                self.eq(
                    size_t,
                    mk_type(Type::Int32),
                    arena.locs[*size],
                    "array size must be an i32",
                );

                // Extract constant size when available (e.g. [0; 5]).
                let array_size = match &arena[*size] {
                    Expr::Int(n) => ArraySize::Known(*n as i32),
                    Expr::UInt(n) => ArraySize::Known(*n as i32),
                    _ => ArraySize::Known(0),
                };

                mk_type(Type::Array(value_t, array_size))
            }
            Expr::While(cond, body) => {
                let cond_t = self.check_expr(*cond, arena, decls);
                self.eq(
                    cond_t,
                    mk_type(Type::Bool),
                    arena.locs[*cond],
                    "while loop control must be a bool",
                );
                self.loop_depth += 1;
                self.check_expr(*body, arena, decls);
                self.loop_depth -= 1;
                mk_type(Type::Void)
            }
            Expr::If(cond, then_expr, else_expr) => {
                let cond_t = self.check_expr(*cond, arena, decls);
                self.eq(
                    cond_t,
                    mk_type(Type::Bool),
                    arena.locs[*cond],
                    "if expression conditional must be a bool",
                );
                let then_t = self.check_expr(*then_expr, arena, decls);
                if let Some(else_expr) = else_expr {
                    self.check_expr(*else_expr, arena, decls);
                    // The if-else expression has the type of its then-branch.
                    then_t
                } else {
                    mk_type(Type::Void)
                }
            }
            Expr::For {
                var,
                start,
                end,
                body,
            } => {
                let ty = mk_type(Type::Int32);
                let start_t = self.check_expr(*start, arena, decls);
                let end_t = self.check_expr(*end, arena, decls);
                self.eq(
                    start_t,
                    ty,
                    arena.locs[*start],
                    "start of for loop must be an integer",
                );
                self.eq(
                    end_t,
                    ty,
                    arena.locs[*start],
                    "end of for loop must be an integer",
                );

                self.vars.push(Var {
                    name: *var,
                    ty,
                    mutable: false,
                });

                self.loop_depth += 1;
                self.check_expr(*body, arena, decls);
                self.loop_depth -= 1;

                self.vars.pop();

                mk_type(Type::Void)
            }
            Expr::Tuple(exprs) => {
                let mut types = vec![];
                for e in exprs {
                    types.push(self.check_expr(*e, arena, decls));
                }
                mk_type(Type::Tuple(types))
            }
            Expr::Lambda { params, body } => {
                let n = self.vars.len();
                let mut param_types = vec![];
                for param in params {
                    let ty = param.ty.unwrap_or_else(|| self.fresh());
                    self.vars.push(Var {
                        name: param.name,
                        mutable: false,
                        ty,
                    });
                    param_types.push(ty);
                }

                let rt = self.check_expr(*body, arena, decls);

                while self.vars.len() > n {
                    self.vars.pop();
                }

                func(tuple(param_types), rt)
            }
            Expr::Error => self.fresh(),
        };
        self.types[id] = ty;
        ty
    }

    fn find(&self, name: Name) -> Option<Var> {
        for v in self.vars.iter().rev() {
            if v.name == name {
                return Some(*v);
            }
        }
        None
    }

    fn check_fn_decl(&mut self, func_decl: &FuncDecl, decls: &DeclTable) {
        // Disallow slice types in return position.
        if type_contains_bad_slice(func_decl.ret) {
            self.errors.push(TypeError {
                location: func_decl.loc,
                message: format!(
                    "slice type {} is not allowed as a return type",
                    func_decl.ret.pretty_print()
                ),
            });
        }

        let n = func_decl.arena.exprs.len();
        self.types.resize(n, mk_type(Type::Void));
        self.lvalue.resize(n, false);

        if let Some(body) = func_decl.body {
            // println!("🟧 checking function {:?} 🟧", *func_decl.name);

            self.inst.clear();
            self.constraints.clear();

            for param in &func_decl.params {
                let ty = match param.ty {
                    Some(ty) => ty,
                    None => {
                        self.errors.push(TypeError {
                            location: func_decl.loc,
                            message: format!(
                                "parameter '{}' is missing a type annotation",
                                *param.name
                            ),
                        });
                        return;
                    }
                };
                self.vars.push(Var {
                    name: param.name,
                    ty,
                    mutable: false,
                });
            }

            // Size variables are available as i32 values in the body.
            for &sv in &func_decl.size_vars {
                self.vars.push(Var {
                    name: sv,
                    ty: mk_type(Type::Int32),
                    mutable: false,
                });
            }

            // Add interface functions to available functions.
            for constraint in &func_decl.constraints {
                if let Some(Decl::Interface(interface)) =
                    decls.find(constraint.interface_name).first()
                {
                    let mut inst = Instance::new();

                    interface
                        .typevars
                        .iter()
                        .zip(&constraint.typevars)
                        .for_each(|pair| {
                            let t0 = mk_type(Type::Var(*pair.0));
                            let t1 = mk_type(Type::Var(*pair.1));
                            if t0 != t1 {
                                inst.insert(t0, t1);
                            }
                        });

                    for func in &interface.funcs {
                        self.vars.push(Var {
                            name: func.name,
                            ty: func.ty().subst(&inst),
                            mutable: false,
                        });
                    }
                } else {
                    self.errors.push(TypeError {
                        location: func_decl.loc,
                        message: format!("unknown interface: {}", constraint.interface_name),
                    })
                }
            }

            // Check the body of the function.
            let ty = self.check_expr(body, &func_decl.arena, decls);

            if func_decl.ret != mk_type(Type::Void) {
                self.eq(
                    ty,
                    func_decl.ret,
                    func_decl.arena.locs[body],
                    "return type must match function return type",
                );
            }

            self.vars.clear();

            if self.errors.is_empty() {
                solve_constraints(
                    &mut self.constraints,
                    &mut self.inst,
                    decls,
                    &mut self.errors,
                );
            }

            // Check lvalue validity now that types are solved.
            if self.errors.is_empty() {
                self.check_lvalues(func_decl);
            }

            // Check that no two slice parameters alias (Fortran-style no-alias rule).
            if self.errors.is_empty() {
                self.check_slice_aliasing(func_decl, decls);
            }
        }
    }

    /// Check that all assignments have valid lvalue targets, using solved types
    /// to determine slice mutability.
    fn check_lvalues(&mut self, func_decl: &FuncDecl) {
        for id in 0..func_decl.arena.exprs.len() {
            if let Expr::Binop(Binop::Assign, lhs, _) = &func_decl.arena[id] {
                if !self.is_lvalue(*lhs, func_decl) {
                    self.errors.push(TypeError {
                        location: func_decl.arena.locs[id],
                        message: "left-hand side of assignment isn't assignable".to_string(),
                    });
                }
            }
        }
    }

    /// Enforce the no-alias rule: two slice parameters in the same call must not
    /// refer to the same underlying memory. Since Lyte has no sub-slicing, two
    /// arguments alias iff they are the same variable (or same field path).
    ///
    /// This enables Fortran-style `restrict` semantics: the compiler (and LLVM
    /// backend) can assume slice parameters never overlap, enabling load hoisting,
    /// store reordering, and vectorization.
    fn check_slice_aliasing(&mut self, func_decl: &FuncDecl, decls: &DeclTable) {
        for id in 0..func_decl.arena.exprs.len() {
            let Expr::Call(f, args) = &func_decl.arena[id] else {
                continue;
            };

            // Only check direct named calls — indirect calls (lambdas) can't
            // have slice parameters (slices can't appear in function types).
            let Expr::Id(callee_name) = &func_decl.arena[*f] else {
                continue;
            };

            // Find which parameter positions are slices in the callee's declaration.
            // For overloaded functions, union all slice positions (conservative).
            let callee_decls = decls.find(*callee_name);
            let mut slice_positions: Vec<usize> = Vec::new();
            for d in callee_decls {
                if let Decl::Func(fd) = d {
                    for (i, param) in fd.params.iter().enumerate() {
                        if let Some(ty) = param.ty {
                            if matches!(*ty, Type::Slice(_)) && !slice_positions.contains(&i) {
                                slice_positions.push(i);
                            }
                        }
                    }
                }
            }

            if slice_positions.len() < 2 {
                continue;
            }

            // Collect (position, base_path) for arguments at slice positions.
            let mut slice_args: Vec<(usize, Vec<Name>)> = Vec::new();
            for &pos in &slice_positions {
                if pos < args.len() {
                    if let Some(path) = expr_base_path(args[pos], &func_decl.arena) {
                        slice_args.push((pos, path));
                    }
                }
            }

            // Check all pairs for aliasing.
            for i in 0..slice_args.len() {
                for j in (i + 1)..slice_args.len() {
                    if slice_args[i].1 == slice_args[j].1 {
                        let name = slice_args[i]
                            .1
                            .iter()
                            .map(|n| n.as_str())
                            .collect::<Vec<_>>()
                            .join(".");
                        self.errors.push(TypeError {
                            location: func_decl.arena.locs[id],
                            message: format!(
                                "cannot pass '{}' to multiple slice parameters \
                                 (slices must not alias)",
                                name
                            ),
                        });
                    }
                }
            }
        }
    }

    /// Determine if an expression is an lvalue, using solved types.
    fn is_lvalue(&self, id: ExprID, func_decl: &FuncDecl) -> bool {
        match &func_decl.arena[id] {
            Expr::Id(_) => self.lvalue[id],
            Expr::Field(lhs, _) => self.is_lvalue(*lhs, func_decl),
            Expr::ArrayIndex(array_expr, _) => {
                // Slice indexing is always an lvalue (slices are mutable references).
                let solved_ty = self.types[*array_expr].subst(&self.inst);
                if matches!(*solved_ty, Type::Slice(_)) {
                    return true;
                }
                // Array indexing is an lvalue only if the array itself is.
                self.is_lvalue(*array_expr, func_decl)
            }
            _ => false,
        }
    }

    fn check_struct_decl(&mut self, st: &StructDecl, decls: &DeclTable) {
        let mut names = HashSet::new();

        for field in &st.fields {
            if names.contains(&field.name) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!("repeated field: {}", &field.name),
                })
            } else {
                names.insert(field.name);
            }

            field.ty.typevars(&mut |name| {
                if !st.typevars.iter().any(|n| *n == name) {
                    self.errors.push(TypeError {
                        location: field.loc,
                        message: format!("unknown type variable: {}", name),
                    })
                }
            })
        }

        // Disallow slice types in struct fields.
        for field in &st.fields {
            if type_contains_bad_slice(field.ty) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!(
                        "slice type {} is not allowed in struct fields (use a sized array instead)",
                        field.ty.pretty_print()
                    ),
                })
            }
        }

        // Disallow recursive struct definitions (they would be unbounded in size).
        let mut visiting = HashSet::new();
        visiting.insert(st.name);
        for field in &st.fields {
            if type_is_recursive(field.ty, decls, &mut visiting) {
                self.errors.push(TypeError {
                    location: field.loc,
                    message: format!("struct '{}' is recursive", st.name),
                });
                break;
            }
        }
    }

    fn check_interface(&mut self, _name: Name, funcs: &[FuncDecl]) {
        for func in funcs {
            if func.body.is_some() {
                self.errors.push(TypeError {
                    location: func.loc,
                    message: format!("interface function can't have body: {}", func.name),
                })
            }
        }
    }

    fn _check_decl(&mut self, decl: &Decl, decls: &DeclTable) {
        match decl {
            Decl::Func(func_decl) => self.check_fn_decl(func_decl, decls),
            Decl::Macro(func_decl) => self.check_fn_decl(func_decl, decls),
            Decl::Interface(Interface { name, funcs, .. }) => self.check_interface(*name, funcs),
            Decl::Struct(struct_decl) => self.check_struct_decl(struct_decl, decls),
            _ => (),
        }
    }

    pub fn check(&mut self, decls: &DeclTable) {
        for decl in &decls.decls {
            self._check_decl(decl, decls);
            // After type-checking each function, verify closures don't escape.
            if let Decl::Func(fd) | Decl::Macro(fd) = decl {
                check_escape_in_func(fd, &mut self.errors);
            }
        }
    }

    pub fn check_decl(&mut self, decl: &Decl, decls: &DeclTable) {
        self._check_decl(decl, decls);
        if let Decl::Func(fd) | Decl::Macro(fd) = decl {
            check_escape_in_func(fd, &mut self.errors);
        }
    }

    /// Returns types we've solved for.
    pub fn solved_types(&self) -> Vec<TypeID> {
        self.types.iter().map(|t| t.subst(&self.inst)).collect()
    }

    pub fn print_errors(&self) {
        for err in &self.errors {
            print_error_with_context(err.location, &err.message);
        }
    }
}

/// Extract the "base path" of an expression — the chain of identifiers and field
/// names that uniquely identifies the storage location. Returns None for complex
/// expressions (calls, indexing, literals) where aliasing can't be determined
/// syntactically.
///
/// Examples:
///   `x`       → Some(["x"])
///   `s.arr`   → Some(["s", "arr"])
///   `f(x)`    → None
///   `a[i]`    → None
fn expr_base_path(id: ExprID, arena: &ExprArena) -> Option<Vec<Name>> {
    match &arena[id] {
        Expr::Id(name) => Some(vec![*name]),
        Expr::Field(base, field) => {
            let mut path = expr_base_path(*base, arena)?;
            path.push(*field);
            Some(path)
        }
        _ => None,
    }
}

/// Verify that no capturing lambda (one with free variables from the enclosing
/// function) escapes the function, either directly returned or via a variable.
/// Such a closure would capture stack addresses that dangle after the frame exits.
fn check_escape_in_func(func_decl: &FuncDecl, errors: &mut Vec<TypeError>) {
    let Some(body) = func_decl.body else {
        return;
    };
    let mut scope: HashSet<String> = func_decl
        .params
        .iter()
        .map(|p| p.name.to_string())
        .collect();
    let mut tainted: HashSet<String> = HashSet::new();
    escape_walk(body, &func_decl.arena, &mut scope, &mut tainted, errors);
}

/// Walk `expr` tracking:
/// - `scope`: all names declared in the enclosing function (used by lambda capture detection)
/// - `tainted`: names that are bound to a capturing lambda and must not be returned
fn escape_walk(
    expr: ExprID,
    arena: &ExprArena,
    scope: &mut HashSet<String>,
    tainted: &mut HashSet<String>,
    errors: &mut Vec<TypeError>,
) {
    match &arena[expr] {
        Expr::Return(e) => {
            // Walk first so any declarations inside `e` update `tainted`.
            escape_walk(*e, arena, scope, tainted, errors);
            if expr_is_tainted(*e, arena, scope, tainted) {
                errors.push(TypeError {
                    location: arena.locs[*e],
                    message: "closure with captured variables cannot be returned \
                              (captured addresses would dangle after the frame exits)"
                        .to_string(),
                });
            }
        }
        Expr::Lambda { .. } => {
            // Do not recurse into the lambda body — it is a separate scope.
        }
        Expr::Block(exprs) => {
            let saved = scope.clone();
            for e in exprs {
                escape_walk(*e, arena, scope, tainted, errors);
            }
            *scope = saved;
        }
        Expr::Let(name, init, _) => {
            escape_walk(*init, arena, scope, tainted, errors);
            if expr_is_tainted(*init, arena, scope, tainted) {
                tainted.insert(name.to_string());
            }
            scope.insert(name.to_string());
        }
        Expr::Var(name, init, _) => {
            if let Some(init_id) = init {
                escape_walk(*init_id, arena, scope, tainted, errors);
                if expr_is_tainted(*init_id, arena, scope, tainted) {
                    tainted.insert(name.to_string());
                }
            }
            scope.insert(name.to_string());
        }
        Expr::If(cond, then, else_) => {
            escape_walk(*cond, arena, scope, tainted, errors);
            escape_walk(*then, arena, scope, tainted, errors);
            if let Some(e) = else_ {
                escape_walk(*e, arena, scope, tainted, errors);
            }
        }
        Expr::While(cond, body) => {
            escape_walk(*cond, arena, scope, tainted, errors);
            escape_walk(*body, arena, scope, tainted, errors);
        }
        Expr::For {
            var,
            start,
            end,
            body,
        } => {
            escape_walk(*start, arena, scope, tainted, errors);
            escape_walk(*end, arena, scope, tainted, errors);
            scope.insert(var.to_string());
            escape_walk(*body, arena, scope, tainted, errors);
        }
        Expr::Call(f, args) => {
            escape_walk(*f, arena, scope, tainted, errors);
            for a in args {
                escape_walk(*a, arena, scope, tainted, errors);
            }
        }
        Expr::Binop(_, lhs, rhs) => {
            escape_walk(*lhs, arena, scope, tainted, errors);
            escape_walk(*rhs, arena, scope, tainted, errors);
        }
        Expr::Unop(_, arg) => escape_walk(*arg, arena, scope, tainted, errors),
        Expr::Field(e, _) | Expr::AsTy(e, _) | Expr::Arena(e) => {
            escape_walk(*e, arena, scope, tainted, errors);
        }
        Expr::ArrayIndex(arr, idx) | Expr::Array(arr, idx) => {
            escape_walk(*arr, arena, scope, tainted, errors);
            escape_walk(*idx, arena, scope, tainted, errors);
        }
        Expr::ArrayLiteral(elems) | Expr::Tuple(elems) => {
            for e in elems {
                escape_walk(*e, arena, scope, tainted, errors);
            }
        }
        Expr::StructLit(_, fields) => {
            for (_, fval) in fields {
                escape_walk(*fval, arena, scope, tainted, errors);
            }
        }
        Expr::Macro(_, args) => {
            for a in args {
                escape_walk(*a, arena, scope, tainted, errors);
            }
        }
        _ => {}
    }
}

/// Returns true if `expr` might produce a capturing lambda value:
/// - a lambda literal whose body references names from `scope` beyond its own params
/// - an identifier in `tainted` (bound to a capturing lambda earlier)
/// - a block or if/else whose value branch is tainted
fn expr_is_tainted(
    expr: ExprID,
    arena: &ExprArena,
    scope: &HashSet<String>,
    tainted: &HashSet<String>,
) -> bool {
    match &arena[expr] {
        Expr::Lambda { params, body } => {
            let lambda_params: HashSet<String> =
                params.iter().map(|p| p.name.to_string()).collect();
            lambda_has_captures(*body, arena, &lambda_params, scope)
        }
        Expr::Id(name) => tainted.contains(&name.to_string()),
        Expr::Block(exprs) => exprs
            .last()
            .map_or(false, |e| expr_is_tainted(*e, arena, scope, tainted)),
        Expr::If(_, then, else_) => {
            expr_is_tainted(*then, arena, scope, tainted)
                || else_.map_or(false, |e| expr_is_tainted(e, arena, scope, tainted))
        }
        // Conservatively: if a tainted value flows into a call (as the function
        // expression or as any argument), the result is also considered tainted.
        // This catches laundering patterns like `return launder(f)` where `f` is
        // a capturing lambda.
        Expr::Call(fn_expr, args) => {
            expr_is_tainted(*fn_expr, arena, scope, tainted)
                || args
                    .iter()
                    .any(|a| expr_is_tainted(*a, arena, scope, tainted))
        }
        _ => false,
    }
}

/// Returns true if `body` (the lambda body) references any name that is in
/// `outer_scope` but not in `lambda_params`.
fn lambda_has_captures(
    body: ExprID,
    arena: &ExprArena,
    lambda_params: &HashSet<String>,
    outer_scope: &HashSet<String>,
) -> bool {
    match &arena[body] {
        Expr::Id(name) => {
            let s = name.to_string();
            outer_scope.contains(&s) && !lambda_params.contains(&s)
        }
        Expr::Binop(_, lhs, rhs) => {
            lambda_has_captures(*lhs, arena, lambda_params, outer_scope)
                || lambda_has_captures(*rhs, arena, lambda_params, outer_scope)
        }
        Expr::Unop(_, arg) => lambda_has_captures(*arg, arena, lambda_params, outer_scope),
        Expr::Call(f, args) => {
            lambda_has_captures(*f, arena, lambda_params, outer_scope)
                || args
                    .iter()
                    .any(|a| lambda_has_captures(*a, arena, lambda_params, outer_scope))
        }
        Expr::Block(exprs) => exprs
            .iter()
            .any(|e| lambda_has_captures(*e, arena, lambda_params, outer_scope)),
        Expr::If(cond, then, else_) => {
            lambda_has_captures(*cond, arena, lambda_params, outer_scope)
                || lambda_has_captures(*then, arena, lambda_params, outer_scope)
                || else_
                    .map(|e| lambda_has_captures(e, arena, lambda_params, outer_scope))
                    .unwrap_or(false)
        }
        Expr::Return(e) | Expr::Field(e, _) | Expr::AsTy(e, _) | Expr::Arena(e) => {
            lambda_has_captures(*e, arena, lambda_params, outer_scope)
        }
        Expr::While(cond, body) | Expr::ArrayIndex(cond, body) | Expr::Array(cond, body) => {
            lambda_has_captures(*cond, arena, lambda_params, outer_scope)
                || lambda_has_captures(*body, arena, lambda_params, outer_scope)
        }
        Expr::For {
            start, end, body, ..
        } => {
            lambda_has_captures(*start, arena, lambda_params, outer_scope)
                || lambda_has_captures(*end, arena, lambda_params, outer_scope)
                || lambda_has_captures(*body, arena, lambda_params, outer_scope)
        }
        Expr::Let(_, init, _) => lambda_has_captures(*init, arena, lambda_params, outer_scope),
        Expr::Var(_, init, _) => init
            .map(|e| lambda_has_captures(e, arena, lambda_params, outer_scope))
            .unwrap_or(false),
        Expr::ArrayLiteral(elems) | Expr::Tuple(elems) => elems
            .iter()
            .any(|e| lambda_has_captures(*e, arena, lambda_params, outer_scope)),
        Expr::StructLit(_, fields) => fields
            .iter()
            .any(|(_, fval)| lambda_has_captures(*fval, arena, lambda_params, outer_scope)),
        Expr::Macro(_, args) => args
            .iter()
            .any(|a| lambda_has_captures(*a, arena, lambda_params, outer_scope)),
        Expr::Lambda { params, body } => {
            // Nested lambda: extend lambda_params with nested params.
            let mut inner_params = lambda_params.clone();
            for p in params {
                inner_params.insert(p.name.to_string());
            }
            lambda_has_captures(*body, arena, &inner_params, outer_scope)
        }
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub fn check(s: &str) -> Vec<TypeError> {
        let mut errors = vec![];
        let decls = parse_program_str(&s, &mut errors);
        assert!(errors.is_empty());

        let mut result = vec![];

        let table = DeclTable::new(decls);
        for decl in &table.decls {
            let mut type_checker = Checker::new();
            type_checker.check_decl(decl, &table);
            type_checker.print_errors();
            result.append(&mut type_checker.errors);
        }

        result
    }

    #[test]
    pub fn test_recursive_struct_direct() {
        // struct A { x: A } — direct self-reference
        let s = "struct A { x: A }";
        let errors = check(s);
        assert!(!errors.is_empty(), "expected an error for recursive struct");
        assert!(errors[0].message.contains("recursive"));
    }

    #[test]
    pub fn test_recursive_struct_indirect() {
        // struct A { b: B }  struct B { a: A } — mutual recursion
        let s = "struct A { b: B }\nstruct B { a: A }";
        let errors = check(s);
        assert!(
            !errors.is_empty(),
            "expected an error for mutually recursive structs"
        );
    }

    #[test]
    pub fn test_recursive_struct_array() {
        // struct A { x: [A; 5] } — self-reference inside a fixed-size array
        let s = "struct A { x: [A; 5] }";
        let errors = check(s);
        assert!(
            !errors.is_empty(),
            "expected an error for recursive struct via array"
        );
        assert!(errors[0].message.contains("recursive"));
    }

    #[test]
    pub fn test_non_recursive_struct() {
        // struct Point { x: i32, y: i32 } — not recursive
        let s = "struct Point { x: i32, y: i32 }";
        let errors = check(s);
        assert!(
            errors.is_empty(),
            "expected no errors for non-recursive struct"
        );
    }

    #[test]
    pub fn test_non_recursive_struct_field() {
        // struct A { b: B }  struct B { x: i32 } — not recursive
        let s = "struct A { b: B }\nstruct B { x: i32 }";
        let errors = check(s);
        assert!(
            errors.is_empty(),
            "expected no errors for non-recursive struct chain"
        );
    }

    #[test]
    pub fn test_array_if() {
        let s = "
        f(i: i32) {
            var a: [i32; 100]
            if i >= 0 && i < 100 {
                a[i]
            }
        }
        ";

        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_inc_i32() {
        let s = "
        f {
            var i: i32
            i = i + 1
        }
        ";

        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_slice_in_struct_field() {
        let s = "struct Bad { x: [i32] }";
        let errors = check(s);
        assert!(
            !errors.is_empty(),
            "expected an error for slice in struct field"
        );
        assert!(errors[0].message.contains("slice type"));
    }

    #[test]
    pub fn test_slice_return_type() {
        let s = "f(a: [i32]) -> [i32] { a }";
        let errors = check(s);
        assert!(
            !errors.is_empty(),
            "expected an error for slice return type"
        );
        assert!(errors[0].message.contains("slice type"));
    }

    #[test]
    pub fn test_slice_param_allowed() {
        let s = "f(a: [i32]) -> i32 { a[0] }";
        let errors = check(s);
        assert!(errors.is_empty(), "slice parameters should be allowed");
    }

    #[test]
    pub fn test_nested_slice_in_struct() {
        let s = "struct Bad { x: [[i32]; 5] }";
        let errors = check(s);
        assert!(
            !errors.is_empty(),
            "expected an error for nested slice in struct field"
        );
        assert!(errors[0].message.contains("slice type"));
    }

    // --- Escape analysis tests ---

    #[test]
    pub fn test_escape_direct_return_capturing_lambda() {
        let s = "
        f() → void → i32 {
            var x = 0
            return (| | x)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_non_capturing_lambda_safe() {
        let s = "
        f() → i32 → i32 {
            return (|x| x * 2)
        }
        ";
        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_escape_let_then_return() {
        let s = "
        f() → i32 → i32 {
            var x = 42
            let g = (|y| x + y)
            return g
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_var_then_return() {
        let s = "
        f() → i32 → i32 {
            var x = 42
            var g = (|y| x + y)
            return g
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_capturing_param() {
        // Capturing a function parameter (still a local stack frame variable)
        let s = "
        f(x: i32) → void → i32 {
            return (| | x)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_if_one_branch_captures() {
        // Only one branch returns a capturing lambda — still an error
        let s = "
        f(flag: i32) → i32 → i32 {
            var x = 10
            if flag > 0 {
                return (|y| x + y)
            } else {
                return (|y| y)
            }
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_both_branches_safe() {
        // Both branches return non-capturing lambdas
        let s = "
        f(flag: i32) → i32 → i32 {
            if flag > 0 {
                return (|y| y * 2)
            } else {
                return (|y| y * 3)
            }
        }
        ";
        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_escape_tainted_through_if_expr() {
        // Tainted value flows through if/else expression
        let s = "
        f(flag: i32) → i32 → i32 {
            var x = 5
            let cap = (|y| x + y)
            let safe = (|y| y)
            let chosen = if flag > 0 { cap } else { safe }
            return chosen
        }
        ";
        let errors = check(s);
        // One escape error, plus one ambiguous type constraint
        assert!(errors.iter().any(|e| e.message.contains("captured")));
    }

    #[test]
    pub fn test_escape_launder_through_call() {
        // Passing a capturing lambda through a function call should be caught
        let s = "
        id(f: i32 → i32) → i32 → i32 { return f }
        f() → i32 → i32 {
            var x = 1
            return id((|y| x + y))
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
    }

    #[test]
    pub fn test_escape_used_locally_safe() {
        // Capturing lambda used locally (called, not returned) is fine
        // as long as the result is not itself returned as a tainted value.
        // Note: the checker conservatively taints call results when the callee
        // is tainted, so `return g(5)` where g is tainted triggers a false positive.
        // Use a var instead to avoid that.
        let s = "
        f() → i32 {
            var x = 10
            var g = (|y| x + y)
            let result = g(5)
            result
        }
        ";
        let errors = check(s);
        // The call result `g(5)` is conservatively tainted, but since it's not
        // explicitly returned via `return`, the implicit return doesn't trigger.
        // This test documents the current behavior.
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_escape_multiple_captures() {
        // Lambda capturing multiple local variables
        let s = "
        f() → void → i32 {
            var a = 1
            var b = 2
            var c = 3
            return (| | a + b + c)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_nested_lambda_captures_outer() {
        // Nested lambda that captures from the enclosing function.
        // The outer lambda captures x, so returning it is an error.
        let s = "
        f() → i32 → i32 {
            var x = 42
            return (|y| x + y)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_nested_non_capturing_safe() {
        // Returned lambda doesn't capture anything from the enclosing function
        let s = "
        f() → i32 → i32 {
            return (|x| x + 1)
        }
        ";
        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_escape_lambda_only_captures_own_param() {
        // Lambda uses its own parameter, not outer scope — safe
        let s = "
        f() → i32 → i32 {
            return (|x| x + 1)
        }
        ";
        let errors = check(s);
        assert!(errors.is_empty());
    }

    #[test]
    pub fn test_escape_return_in_while_loop() {
        // Returning a capturing lambda from inside a while loop
        let s = "
        f(n: i32) → void → i32 {
            var x = 0
            while x < n {
                return (| | x)
            }
            return (| | 0)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("captured"));
    }

    #[test]
    pub fn test_escape_return_in_for_loop() {
        // Returning a capturing lambda from inside a for loop
        let s = "
        f() → void → i32 {
            var x = 99
            for i in 0 .. 10 {
                return (| | x)
            }
            return (| | 0)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
    }

    #[test]
    pub fn test_escape_two_returns_two_errors() {
        // Two separate return statements with capturing lambdas = two errors
        let s = "
        f(flag: i32) → void → i32 {
            var x = 1
            var y = 2
            if flag > 0 {
                return (| | x)
            }
            return (| | y)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 2);
    }

    #[test]
    pub fn test_escape_taint_does_not_leak_across_functions() {
        // A tainted variable in one function should not affect another
        let s = "
        good() → i32 → i32 {
            return (|x| x + 1)
        }
        bad() → void → i32 {
            var x = 0
            return (| | x)
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1); // only bad() should fail
    }

    #[test]
    pub fn test_escape_binop_with_tainted() {
        // Assigning tainted via a let, then returning — should still catch
        let s = "
        f() → i32 → i32 {
            var x = 5
            let g = (|y| x + y)
            let h = g
            return h
        }
        ";
        let errors = check(s);
        assert_eq!(errors.len(), 1);
    }

    #[test]
    pub fn test_escape_for_loop_var_capture() {
        // Lambda captures the for-loop variable — should error
        let s = "
        f() → void → i32 {
            for i in 0 .. 10 {
                return (| | i)
            }
            return (| | 0)
        }
        ";
        let errors = check(s);
        // i is in scope inside the for body, so capturing it should be caught
        assert!(errors.len() >= 1);
    }
}
