// ============================================================================
// Generated by scripts/gen_fused_handlers.py from src/stack_interp.c.
// DO NOT EDIT MANUALLY — regenerate via the script.
//
// Each handler below is the concatenation of one or more base-op bodies,
// with pc->imm[0] references rewritten per the fusion spec and intermediate
// NEXT() tail-calls stripped. Correctness relies on clang's store-to-load
// forwarding + DCE folding the PUSH/POP spills that appear between base-op
// bodies into the same machine code as the hand-written combined forms.
//
// This file is a standalone translation unit — the shared handler macros
// (HANDLER, NEXT, PUSH/POP, READ_I/WRITE_I, HOT_L*_MAGIC, ...) and type
// definitions live in stack_interp.h.
// ============================================================================

#include "stack_interp.h"

// op_local_get@0 + op_local_get@1 + op_iadd
HANDLER(op_fused_get_get_iadd) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_get (pc->imm[1]) ---
    PUSH(READ_I(pc->imm[1]));

    // --- op_iadd ---
    t0 = (uint64_t)((int64_t)t1 + (int64_t)t0);
    BINOP_SHIFT();
    NEXT();
}

// op_local_get@0 + op_local_get@1 + op_ilt
HANDLER(op_fused_get_get_ilt) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_get (pc->imm[1]) ---
    PUSH(READ_I(pc->imm[1]));

    // --- op_ilt ---
    int64_t b = (int64_t)(t0); int64_t a = (int64_t)(t1);
    t0 = (a < b) ? 1 : 0;
    BINOP_SHIFT();
    NEXT();
}

// op_local_get@0 + op_iadd_imm@1 + op_local_set@2
HANDLER(op_fused_get_addimm_set) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_iadd_imm (pc->imm[1]) ---
    t0 = (uint64_t)((int64_t)t0 + (int64_t)pc->imm[1]);

    // --- op_local_set (pc->imm[2]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[2], val);
    NEXT();
}

// op_i64_const@0 + op_local_set@1
HANDLER(op_fused_const_set) {
    // --- op_i64_const (pc->imm[0]) ---
    PUSH(pc->imm[0]);

    // --- op_local_set (pc->imm[1]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[1], val);
    NEXT();
}

// op_local_get@0 + op_local_set@1
HANDLER(op_fused_get_set) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_set (pc->imm[1]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[1], val);
    NEXT();
}

// op_local_get@0 + op_local_get@1 + op_iadd + op_local_set@2
HANDLER(op_fused_get_get_iadd_set) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_get (pc->imm[1]) ---
    PUSH(READ_I(pc->imm[1]));

    // --- op_iadd ---
    t0 = (uint64_t)((int64_t)t1 + (int64_t)t0);
    BINOP_SHIFT();

    // --- op_local_set (pc->imm[2]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[2], val);
    NEXT();
}

// op_local_get@0 + op_local_get@1 + op_isub + op_local_set@2
HANDLER(op_fused_get_get_isub_set) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_get (pc->imm[1]) ---
    PUSH(READ_I(pc->imm[1]));

    // --- op_isub ---
    t0 = (uint64_t)((int64_t)t1 - (int64_t)t0);
    BINOP_SHIFT();

    // --- op_local_set (pc->imm[2]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[2], val);
    NEXT();
}

// op_local_get@0 + op_local_get@1 + op_imul + op_local_set@2
HANDLER(op_fused_get_get_imul_set) {
    // --- op_local_get (pc->imm[0]) ---
    PUSH(READ_I(pc->imm[0]));

    // --- op_local_get (pc->imm[1]) ---
    PUSH(READ_I(pc->imm[1]));

    // --- op_imul ---
    t0 = (uint64_t)((int64_t)t1 * (int64_t)t0);
    BINOP_SHIFT();

    // --- op_local_set (pc->imm[2]) ---
    uint64_t val; POP(val);
    WRITE_I(pc->imm[2], val);
    NEXT();
}

// op_local_get_f@0 + op_local_get_f@1 + op_fadd_f
HANDLER(op_fused_get_get_fadd_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_local_get_f (pc->imm[1]) ---
    FPUSH(READ_F_OFF(pc->imm[1]));

    // --- op_fadd_f ---
    f0 = f1 + f0;
    FBINOP_SHIFT();
    NEXT();
}

// op_local_get_f@0 + op_local_get_f@1 + op_fsub_f
HANDLER(op_fused_get_get_fsub_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_local_get_f (pc->imm[1]) ---
    FPUSH(READ_F_OFF(pc->imm[1]));

    // --- op_fsub_f ---
    f0 = f1 - f0;
    FBINOP_SHIFT();
    NEXT();
}

// op_local_get_f@0 + op_local_get_f@1 + op_fmul_f
HANDLER(op_fused_get_get_fmul_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_local_get_f (pc->imm[1]) ---
    FPUSH(READ_F_OFF(pc->imm[1]));

    // --- op_fmul_f ---
    f0 = f1 * f0;
    FBINOP_SHIFT();
    NEXT();
}

// op_local_get_f@0 + op_fmul_f
HANDLER(op_fused_get_fmul_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_fmul_f ---
    f0 = f1 * f0;
    FBINOP_SHIFT();
    NEXT();
}

// op_local_get_f@0 + op_fadd_f
HANDLER(op_fused_get_fadd_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_fadd_f ---
    f0 = f1 + f0;
    FBINOP_SHIFT();
    NEXT();
}

// op_local_get_f@0 + op_fsub_f
HANDLER(op_fused_get_fsub_f) {
    // --- op_local_get_f (pc->imm[0]) ---
    FPUSH(READ_F_OFF(pc->imm[0]));

    // --- op_fsub_f ---
    f0 = f1 - f0;
    FBINOP_SHIFT();
    NEXT();
}
