// ============================================================================
// Generated by scripts/gen_fused_handlers.py from the FUSIONS spec.
// DO NOT EDIT MANUALLY — regenerate via the script.
//
// Each block below is a peephole-fusion clause that matches a window of
// base StackOps and replaces it with the corresponding fused StackOp. This
// file is embedded via include!() inside stack_optimize.rs's fuse() loop,
// where it relies on the surrounding scope's `ops`, `i`, `len`, and
// `spans_target` closure. Generated rules match the same patterns (and in
// the same priority order — longest first) as the hand-written rules they
// replaced.
// ============================================================================

{
        // op_local_get@0 + op_local_get@1 + op_iadd → FusedGetGetIAdd
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGet(a), StackOp::LocalGet(b), StackOp::IAdd) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetGetIAdd(a, b);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_local_get@0 + op_local_get@1 + op_ilt → FusedGetGetILt
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGet(a), StackOp::LocalGet(b), StackOp::ILt) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetGetILt(a, b);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_local_get@0 + op_iadd_imm@1 + op_local_set@2 → FusedGetAddImmSet
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGet(a), StackOp::IAddImm(b), StackOp::LocalSet(c)) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                let c = *c;
                ops[i] = StackOp::FusedGetAddImmSet(a, b, c);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_local_get_f@0 + op_local_get_f@1 + op_fadd_f → FusedGetGetFAddF
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGetF(a), StackOp::LocalGetF(b), StackOp::FAddF) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetGetFAddF(a, b);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_local_get_f@0 + op_local_get_f@1 + op_fsub_f → FusedGetGetFSubF
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGetF(a), StackOp::LocalGetF(b), StackOp::FSubF) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetGetFSubF(a, b);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_local_get_f@0 + op_local_get_f@1 + op_fmul_f → FusedGetGetFMulF
        if i + 2 < len && !spans_target(i, 3) {
            if let (StackOp::LocalGetF(a), StackOp::LocalGetF(b), StackOp::FMulF) = (&ops[i], &ops[i+1], &ops[i+2]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetGetFMulF(a, b);
                ops[i + 1] = StackOp::Nop;
                ops[i + 2] = StackOp::Nop;
                i += 3;
                continue;
            }
        }

        // op_i64_const@0 + op_local_set@1 → FusedConstSet
        if i + 1 < len && !spans_target(i, 2) {
            if let (StackOp::I64Const(a), StackOp::LocalSet(b)) = (&ops[i], &ops[i+1]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedConstSet(a, b);
                ops[i + 1] = StackOp::Nop;
                i += 2;
                continue;
            }
        }

        // op_local_get@0 + op_local_set@1 → FusedGetSet
        if i + 1 < len && !spans_target(i, 2) {
            if let (StackOp::LocalGet(a), StackOp::LocalSet(b)) = (&ops[i], &ops[i+1]) {
                let a = *a;
                let b = *b;
                ops[i] = StackOp::FusedGetSet(a, b);
                ops[i + 1] = StackOp::Nop;
                i += 2;
                continue;
            }
        }

        // op_local_get_f@0 + op_fmul_f → FusedGetFMulF
        if i + 1 < len && !spans_target(i, 2) {
            if let (StackOp::LocalGetF(a), StackOp::FMulF) = (&ops[i], &ops[i+1]) {
                let a = *a;
                ops[i] = StackOp::FusedGetFMulF(a);
                ops[i + 1] = StackOp::Nop;
                i += 2;
                continue;
            }
        }

        // op_local_get_f@0 + op_fadd_f → FusedGetFAddF
        if i + 1 < len && !spans_target(i, 2) {
            if let (StackOp::LocalGetF(a), StackOp::FAddF) = (&ops[i], &ops[i+1]) {
                let a = *a;
                ops[i] = StackOp::FusedGetFAddF(a);
                ops[i + 1] = StackOp::Nop;
                i += 2;
                continue;
            }
        }

        // op_local_get_f@0 + op_fsub_f → FusedGetFSubF
        if i + 1 < len && !spans_target(i, 2) {
            if let (StackOp::LocalGetF(a), StackOp::FSubF) = (&ops[i], &ops[i+1]) {
                let a = *a;
                ops[i] = StackOp::FusedGetFSubF(a);
                ops[i + 1] = StackOp::Nop;
                i += 2;
                continue;
            }
        }
}
