//! Rebase memory-slot references so they are relative to the frame
//! pointer (fp = start of scalar locals) instead of lm (which used to be
//! a separate buffer).
//!
//! After this pass, ops that used to mean "lm + s*8 + off" are encoded as
//! "fp + s*8 + off" where s has been shifted by `local_count`. This lets
//! us eliminate the `lm` handler argument and allocate locals + local
//! memory contiguously in a single bump buffer.
//!
//! Must run BEFORE fusion — fusion then propagates the rebased offsets
//! into new combined ops without any fusion-rule changes.

use crate::stack_ir::{StackFunction, StackOp};

/// Shift every memory-slot immediate by `local_count` so the slot becomes
/// a u64 slot index relative to the start of the frame (fp).
pub fn rebase(func: &mut StackFunction) {
    let lc = func.local_count;
    if lc == 0 {
        return;
    }
    for op in &mut func.ops {
        match op {
            // `LocalAddr(s)` means lm+s*8 → rebase to fp+s'*8 where s' = s+lc.
            StackOp::LocalAddr(s) => *s += lc,

            // The fused ops below already exist; in the pre-fusion IR they
            // are not generated by codegen yet, but if this pass were ever
            // re-run we handle them defensively.
            StackOp::FusedAddrLoad32Off(s, _) => *s += lc,
            StackOp::FusedAddrLoad32OffSet(s, _, _) => *s += lc,
            StackOp::FusedAddrImmGetStore32(s, _, _) => *s += lc,
            StackOp::FusedAddrGetSliceLoad32(s, _) => *s += lc,
            StackOp::FusedAddrGetSliceStore32(s, _) => *s += lc,
            StackOp::FusedTeeSliceStore32(_, s, _) => *s += lc,
            StackOp::FusedGetAddrFMulFAdd(_, s, _) => *s += lc,
            StackOp::FusedGetAddrFMulFSub(_, s, _) => *s += lc,
            StackOp::FusedFieldCopy32(s, _, _) => *s += lc,
            _ => {}
        }
    }
}
