//! Rebase memory-slot references so they are relative to the frame
//! pointer (fp = start of scalar locals) instead of lm (which used to be
//! a separate buffer).
//!
//! After this pass, ops that used to mean "lm + s*8 + off" are encoded as
//! "fp + s*8 + off" where s has been shifted by `local_count`. This lets
//! us eliminate the `lm` handler argument and allocate locals + local
//! memory contiguously in a single bump buffer.
//!
//! Must run BEFORE fusion — fusion then propagates the rebased offsets
//! into new combined ops without any fusion-rule changes.

use crate::stack_ir::{StackFunction, StackOp};

/// Fill in the `preserve` field of every Call with the number of
/// non-argument TOS values that are live at the call site. At op_call
/// entry the caller's stack depth is D (known statically); the top nargs
/// values are the arguments and the remaining `min(D, 4) - nargs` values
/// below them live in the TOS window and must be written to memory so
/// they survive across the call. Anything deeper than that is already in
/// memory (from earlier deep pushes) and needs no further action.
///
/// At jump targets stack depth is not known (`compute_depths` returns
/// 255); fall back to the conservative `4 - nargs` which is always safe.
pub fn patch_call_preserve(func: &mut StackFunction) {
    let depths = crate::stack_depth::compute_depths(func);
    for (i, op) in func.ops.iter_mut().enumerate() {
        if let StackOp::Call { args, preserve, .. } = op {
            let d = depths[i] as u32;
            let d_clamped = if d >= 4 { 4 } else { d };
            let tos_above_args = d_clamped.saturating_sub(*args as u32);
            *preserve = tos_above_args.min(4) as u8;
        }
    }
}

/// Shift every memory-slot immediate by `local_count` so the slot becomes
/// a u64 slot index relative to the start of the frame (fp).
pub fn rebase(func: &mut StackFunction) {
    let lc = func.local_count;
    if lc == 0 {
        return;
    }
    for op in &mut func.ops {
        match op {
            // `LocalAddr(s)` means lm+s*8 → rebase to fp+s'*8 where s' = s+lc.
            StackOp::LocalAddr(s) => *s += lc,

            // The fused ops below already exist; in the pre-fusion IR they
            // are not generated by codegen yet, but if this pass were ever
            // re-run we handle them defensively.
            StackOp::FusedAddrLoad32Off(s, _) => *s += lc,
            StackOp::FusedAddrLoad32OffSet(s, _, _) => *s += lc,
            StackOp::FusedAddrImmGetStore32(s, _, _) => *s += lc,
            StackOp::FusedAddrGetSliceLoad32(s, _) => *s += lc,
            StackOp::FusedAddrGetSliceStore32(s, _) => *s += lc,
            StackOp::FusedTeeSliceStore32(_, s, _) => *s += lc,
            StackOp::FusedGetAddrFMulFAdd(_, s, _) => *s += lc,
            StackOp::FusedGetAddrFMulFSub(_, s, _) => *s += lc,
            StackOp::FusedFieldCopy32(s, _, _) => *s += lc,
            _ => {}
        }
    }
}
